/**
 * The Champions dataset and its types.
 *
 * `dex.json` is generated by design/pipeline (see design/HANDOFF.md § "如何重建"). It is
 * never hand-edited, and nothing under src/ reaches into design/ to read it.
 *
 * This module is the single place where the untyped JSON payload becomes typed data.
 * The JSON boundary is deliberately `unknown` — see the note in src/shims-vue.d.ts.
 */
import rawDex from './dex.json'
// Type-only elsewhere in this module's dependents, but a value here. Safe from the cycle that
// would otherwise form through i18n: types.ts imports nothing at runtime.
import { typeName } from './types.js'

/** Where a form comes from in the roster table. */
export type FormKind = 'base' | 'other' | 'regional' | 'mega'

/** Six base stats, in HP / Attack / Defense / Sp. Attack / Sp. Defense / Speed order. */
export type StatLine = readonly [number, number, number, number, number, number]

/**
 * An ability slot: an index into {@link Dex.abilities}, plus a second element when the
 * slot holds the species' hidden ability.
 */
export type AbilityRef = readonly [number] | readonly [number, number]

/** How a move deals damage. */
export type MoveClass = 'Physical' | 'Special' | 'Status'

export interface Form {
  /** English form label. Empty for a species' base form. */
  readonly l: string
  /** Chinese form label. Empty for a species' base form. */
  readonly lz: string
  readonly k: FormKind
  /** One or two type names, keyed into the type reference tables. */
  readonly t: readonly string[]
  /** Sprite file name, resolved against the sprite host. */
  readonly s: string
  readonly st: StatLine
  readonly ab: readonly AbilityRef[]
  /** Index into the owning species' {@link Species.sec} learnset sections. */
  readonly si: number
  /** 1 when the sprite is the species' shared artwork because this form has none of its own. */
  readonly a?: 1
  /** 1 when this form sits outside the current roster. */
  readonly x?: 1
  /** Game version that introduced this form, when it differs from the species'. */
  readonly v?: string
}

export interface Species {
  /** National dex number. */
  readonly d: number
  /** English species name. */
  readonly m: string
  /** Chinese species name. */
  readonly mz: string
  /** Chinese category. Empty for species PokeAPI carries no category for. */
  readonly gz: string
  /** Generation number, 1 through 9. */
  readonly g: number
  /** Game version that introduced this species. */
  readonly v: string
  /** 1 when the species sits outside the current roster. */
  readonly x: 0 | 1
  /** Roster note, empty for most species. */
  readonly n: string
  readonly f: readonly Form[]
  /** Learnset sections. Each is a list of indices into {@link Dex.moves}. */
  readonly sec: readonly (readonly number[])[]
}

export interface Move {
  /** English move name. */
  readonly n: string
  /** Chinese move name. Empty for the two moves with no Chinese name yet. */
  readonly z: string
  readonly ty: string
  readonly dc: MoveClass
  /** Power, or null for moves that deal no fixed damage. */
  readonly pw: number | null
  /** Accuracy, or null for moves that never miss. */
  readonly ac: number | null
  readonly pp: number
}

export interface Ability {
  /** English ability name. */
  readonly n: string
  /** Chinese ability name. Empty for the two abilities with no Chinese name yet. */
  readonly z: string
  /** Chinese description. Empty for the 19 abilities with no Chinese description. */
  readonly d: string
  /** English description. Present for all 200 abilities. */
  readonly de: string
}

export interface DexMeta {
  readonly species: number
  readonly formEntries: number
  readonly megas: number
  readonly regional: number
  readonly moves: number
  readonly moveRefs: number
  readonly abilities: number
  readonly zhMoves: number
  readonly zhAbilities: number
  readonly abilDescZh: number
  readonly abilDescEn: number
  /** Which roster the dataset was built from. */
  readonly roster: string
  /** Where each part of the dataset came from. */
  readonly source: string
}

export interface Dex {
  readonly meta: DexMeta
  readonly species: readonly Species[]
  readonly moves: readonly Move[]
  readonly abilities: readonly Ability[]
}

/**
 * Counts the dataset must hit. These exist to catch upstream change, not to make a test
 * pass — read design/HANDOFF.md § "資料層的驗證不變式" before relaxing any of them.
 */
const EXPECTED = {
  'species count': 208,
  'form entries': 360,
  'mega forms': 75,
  'regional forms': 16,
  'move table entries': 496,
  'ability entries': 200,
} as const

function assertCount(invariant: keyof typeof EXPECTED, actual: number): void {
  const expected = EXPECTED[invariant]
  if (actual !== expected) {
    throw new Error(
      `dex dataset invariant violated: ${invariant} — expected ${expected}, actual ${actual}. `
      + 'A mismatch means the dataset changed upstream; read design/HANDOFF.md '
      + '§ "資料層的驗證不變式" before relaxing this.',
    )
  }
}

const dex = rawDex as Dex

let formCount = 0
let megaCount = 0
let regionalCount = 0
for (const species of dex.species) {
  for (const form of species.f) {
    formCount += 1
    if (form.k === 'mega') megaCount += 1
    else if (form.k === 'regional') regionalCount += 1
  }
}

assertCount('species count', dex.species.length)
assertCount('form entries', formCount)
assertCount('mega forms', megaCount)
assertCount('regional forms', regionalCount)
assertCount('move table entries', dex.moves.length)
assertCount('ability entries', dex.abilities.length)

export { dex }

/** Generation numerals, indexed by generation number. Index 0 is unused. */
export const GEN_ROMAN = [
  '', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX',
] as const

/** The generation numeral for a species, or the bare number if it falls outside the table. */
export function genNumeral(species: Species): string {
  return GEN_ROMAN[species.g] ?? String(species.g)
}

/** Total base stats for one form. */
export function bst(form: Form): number {
  let total = 0
  for (const stat of form.st) total += stat
  return total
}

/**
 * The highest base-stat total across a species' forms. Taking the strongest rather than
 * the base form is what keeps every Mega from being buried under low figures when
 * species are ordered by stats.
 */
export function bestBst(species: Species): number {
  let best = 0
  for (const form of species.f) {
    const total = bst(form)
    if (total > best) best = total
  }
  return best
}

/** Every type appearing on any of a species' forms, in first-seen order. */
export function allTypes(species: Species): string[] {
  const seen: string[] = []
  for (const form of species.f) {
    for (const type of form.t) {
      if (!seen.includes(type)) seen.push(type)
    }
  }
  return seen
}

/**
 * Everything about a species that the search string is matched against, lower-cased.
 *
 * One string rather than a field-by-field comparison, because a multi-token query has to be
 * able to name two different things at once: `mega charizard` matches nothing if each token
 * must find one field that holds both.
 *
 * Carries the four things the search field's placeholder names — name, number, type, form —
 * plus the category and generation that travel with them. The number appears twice because
 * the cards print it zero-padded and a reader is as likely to type what they saw.
 *
 * The bare generation numeral is deliberately absent, although the design document's own
 * haystack carries it. A search for `V` would then reach 125 of the 208 species — every name
 * holding the letter — which on screen is indistinguishable from a search that is not
 * working. The `gen<n>` token reaches the same set with nothing to collide with.
 *
 * Built on demand rather than cached. Recomputing 208 of these per keystroke is the same
 * bargain the result sequence already makes; if it ever registers on device, this is the one
 * place that would memoise, because the value depends only on the dataset.
 */
export function searchHaystack(species: Species): string {
  const types = allTypes(species)
  return [
    species.m,
    species.mz,
    species.gz,
    String(species.d),
    String(species.d).padStart(4, '0'),
    `gen${species.g}`,
    ...species.f.map((form) => form.l),
    ...species.f.map((form) => form.lz),
    ...types,
    ...types.map((type) => typeName(type, 'zh')),
  ].join(' ').toLowerCase()
}

/** Whether any of a species' forms is a Mega evolution. */
export function hasMega(species: Species): boolean {
  return species.f.some((form) => form.k === 'mega')
}

/** The species' Mega forms, in dataset order. */
export function megaForms(species: Species): Form[] {
  return species.f.filter((form) => form.k === 'mega')
}

/**
 * Where the artwork is served from.
 *
 * External by design: the sprites are the only thing on screen carrying original colour, and
 * 360 of them would dominate a bundle that is otherwise 195 KB of data.
 */
const SPRITE_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/'

/**
 * The artwork URL for one form.
 *
 * Here rather than in each component that draws artwork: the card and the detail panel show
 * the same sprites at different sizes, and two copies of the host would be two things to
 * change when it moves.
 */
export function spriteUrl(form: Form): string {
  return SPRITE_BASE + form.s
}

/**
 * The ability an ability slot refers to.
 *
 * Slots hold an index into the shared ability table rather than the ability itself, because
 * 360 forms share 200 abilities. Resolving the index here keeps every caller from reaching
 * into {@link Dex.abilities} and repeating the lookup — and from having to decide what an
 * out-of-range index means, which cannot happen: the dataset's ability count is asserted at
 * load, and the pipeline builds these indices from the same table.
 */
export function abilityOf(ref: AbilityRef): Ability {
  const ability = dex.abilities[ref[0]]
  if (ability === undefined) {
    throw new Error(
      `ability slot refers to index ${ref[0]}, which is outside the ability table. `
      + 'A slot and the table it indexes are built together by design/pipeline, so this '
      + 'means the two came from different builds.',
    )
  }
  return ability
}

/**
 * Whether an ability slot holds the species' hidden ability.
 *
 * Encoded as the presence of a second element rather than a flag, which is the dataset's own
 * shape — see {@link AbilityRef}.
 */
export function isHidden(ref: AbilityRef): boolean {
  return ref.length > 1
}

/**
 * The move indices `form` can learn, from the owning species' learnset sections.
 *
 * Resolved here rather than in the table because a section is held on the species while a
 * form holds only an index into those sections — so the table cannot reach one from a form
 * alone, and the alternative is handing the table a species it has no other use for.
 *
 * An out-of-range index yields an empty list instead of throwing, which is the opposite of
 * {@link abilityOf}'s choice and deliberately so. A missing ability leaves nothing to draw,
 * but an empty learnset is a state the table already renders — one species has a single move
 * and the bonus filter empties it entirely. More importantly, a throw inside a computed
 * surfaces on this platform as unexplained broken layout rather than as an error, so failing
 * loudly here would fail invisibly.
 *
 * Megas reuse their base form's section, which is why several forms return the same list.
 */
export function learnsetOf(species: Species, form: Form): readonly number[] {
  return species.sec[form.si] ?? []
}

/**
 * The move at `index` in the shared move table.
 *
 * Learnset sections hold indices rather than moves because 208 sections share 496 moves.
 * Resolving here keeps every caller out of {@link Dex.moves} — the same arrangement, and the
 * same reasoning about an impossible index, as {@link abilityOf}.
 */
export function moveOf(index: number): Move {
  const move = dex.moves[index]
  if (move === undefined) {
    throw new Error(
      `learnset refers to move index ${index}, which is outside the move table. `
      + 'A section and the table it indexes are built together by design/pipeline, so this '
      + 'means the two came from different builds.',
    )
  }
  return move
}
